export const dummyResult = [
  {
    id: 1,
    studentId: "STD-2026-001",
    admissionNo: "ADM24001",
    roll: 1,
    name: "Ayaan Rahman",
    class: "Grade 8",
    section: "A",
    academicYear: "2025-2026",
    examType: "1st Monthly Test",

    totalMarks: 800,
    obtainedMarks: 744,
    percentage: 93,
    gpa: 5.0,
    grade: "A+",
    position: 1,
    attendance: 98,
    status: "Pass",

    subjects: [
      { subject: "English Language", marks: 94, fullMarks: 100, grade: "A+" },
      { subject: "English Literature", marks: 91, fullMarks: 100, grade: "A+" },
      { subject: "Mathematics", marks: 99, fullMarks: 100, grade: "A+" },
      { subject: "General Science", marks: 95, fullMarks: 100, grade: "A+" },
      { subject: "Bangla", marks: 90, fullMarks: 100, grade: "A+" },
      { subject: "Islamic Studies", marks: 96, fullMarks: 100, grade: "A+" },
      { subject: "ICT", marks: 93, fullMarks: 100, grade: "A+" },
      {
        subject: "Arabic",
        marks: 86,
        fullMarks: 100,
        grade: "A",
      },
    ],
  },

  {
    id: 2,
    studentId: "STD-2026-001",
    admissionNo: "ADM24001",
    roll: 1,
    name: "Ayaan Rahman",
    class: "Grade 8",
    section: "A",
    academicYear: "2025-2026",
    examType: "Half Yearly Examination",

    totalMarks: 800,
    obtainedMarks: 761,
    percentage: 95.13,
    gpa: 5,
    grade: "A+",
    position: 1,
    attendance: 98,
    status: "Pass",

    subjects: [
      { subject: "English Language", marks: 95, fullMarks: 100, grade: "A+" },
      { subject: "English Literature", marks: 94, fullMarks: 100, grade: "A+" },
      { subject: "Mathematics", marks: 100, fullMarks: 100, grade: "A+" },
      { subject: "General Science", marks: 96, fullMarks: 100, grade: "A+" },
      { subject: "Bangla", marks: 92, fullMarks: 100, grade: "A+" },
      { subject: "Islamic Studies", marks: 97, fullMarks: 100, grade: "A+" },
      { subject: "ICT", marks: 95, fullMarks: 100, grade: "A+" },
      {
        subject: "Arabic",
        marks: 92,
        fullMarks: 100,
        grade: "A+",
      },
    ],
  },

  {
    id: 3,
    studentId: "STD-2026-001",
    admissionNo: "ADM24001",
    roll: 1,
    name: "Ayaan Rahman",
    class: "Grade 8",
    section: "A",
    academicYear: "2025-2026",
    examType: "Pre-Test Examination",

    totalMarks: 800,
    obtainedMarks: 773,
    percentage: 96.63,
    gpa: 5,
    grade: "A+",
    position: 1,
    attendance: 99,
    status: "Pass",

    subjects: [
      { subject: "English Language", marks: 96, fullMarks: 100, grade: "A+" },
      { subject: "English Literature", marks: 95, fullMarks: 100, grade: "A+" },
      { subject: "Mathematics", marks: 100, fullMarks: 100, grade: "A+" },
      { subject: "General Science", marks: 98, fullMarks: 100, grade: "A+" },
      { subject: "Bangla", marks: 94, fullMarks: 100, grade: "A+" },
      { subject: "Islamic Studies", marks: 98, fullMarks: 100, grade: "A+" },
      { subject: "ICT", marks: 96, fullMarks: 100, grade: "A+" },
      {
        subject: "Arabic",
        marks: 96,
        fullMarks: 100,
        grade: "A+",
      },
    ],
  },

  {
    id: 4,
    studentId: "STD-2026-001",
    admissionNo: "ADM24001",
    roll: 1,
    name: "Ayaan Rahman",
    class: "Grade 8",
    section: "A",
    academicYear: "2025-2026",
    examType: "Final Examination",

    totalMarks: 800,
    obtainedMarks: 782,
    percentage: 97.75,
    gpa: 5,
    grade: "A+",
    position: 1,
    attendance: 99,
    status: "Pass",

    subjects: [
      { subject: "English Language", marks: 98, fullMarks: 100, grade: "A+" },
      { subject: "English Literature", marks: 96, fullMarks: 100, grade: "A+" },
      { subject: "Mathematics", marks: 100, fullMarks: 100, grade: "A+" },
      { subject: "General Science", marks: 99, fullMarks: 100, grade: "A+" },
      { subject: "Bangla", marks: 96, fullMarks: 100, grade: "A+" },
      { subject: "Islamic Studies", marks: 99, fullMarks: 100, grade: "A+" },
      { subject: "ICT", marks: 97, fullMarks: 100, grade: "A+" },
      {
        subject: "Arabic",
        marks: 97,
        fullMarks: 100,
        grade: "A+",
      },
    ],
  },

  {
    id: 5,
    studentId: "STD-2026-002",
    admissionNo: "ADM24002",
    roll: 2,
    name: "Sara Ahmed",
    class: "Grade 8",
    section: "A",
    academicYear: "2025-2026",
    examType: "1st Monthly Test",

    totalMarks: 800,
    obtainedMarks: 722,
    percentage: 90.25,
    gpa: 5,
    grade: "A+",
    position: 2,
    attendance: 97,
    status: "Pass",

    subjects: [
      { subject: "English Language", marks: 91, fullMarks: 100, grade: "A+" },
      { subject: "English Literature", marks: 89, fullMarks: 100, grade: "A" },
      { subject: "Mathematics", marks: 95, fullMarks: 100, grade: "A+" },
      { subject: "General Science", marks: 92, fullMarks: 100, grade: "A+" },
      { subject: "Bangla", marks: 88, fullMarks: 100, grade: "A" },
      { subject: "Islamic Studies", marks: 93, fullMarks: 100, grade: "A+" },
      { subject: "ICT", marks: 90, fullMarks: 100, grade: "A+" },
      {
        subject: "Arabic",
        marks: 84,
        fullMarks: 100,
        grade: "A",
      },
    ],
  },

  {
    id: 6,
    studentId: "STD-2026-002",
    admissionNo: "ADM24002",
    roll: 2,
    name: "Sara Ahmed",
    class: "Grade 8",
    section: "A",
    academicYear: "2025-2026",
    examType: "Half Yearly Examination",
    totalMarks: 800,
    obtainedMarks: 739,
    percentage: 92.38,
    gpa: 5,
    grade: "A+",
    position: 2,
    attendance: 97,
    status: "Pass",
    subjects: [
      { subject: "English Language", marks: 93, fullMarks: 100, grade: "A+" },
      { subject: "English Literature", marks: 91, fullMarks: 100, grade: "A+" },
      { subject: "Mathematics", marks: 97, fullMarks: 100, grade: "A+" },
      { subject: "General Science", marks: 94, fullMarks: 100, grade: "A+" },
      { subject: "Bangla", marks: 90, fullMarks: 100, grade: "A+" },
      { subject: "Islamic Studies", marks: 95, fullMarks: 100, grade: "A+" },
      { subject: "ICT", marks: 92, fullMarks: 100, grade: "A+" },
      {
        subject: "Arabic",
        marks: 87,
        fullMarks: 100,
        grade: "A",
      },
    ],
  },

  {
    id: 7,
    studentId: "STD-2026-003",
    admissionNo: "ADM24003",
    roll: 3,
    name: "Zayan Chowdhury",
    class: "Grade 8",
    section: "A",
    academicYear: "2025-2026",
    examType: "1st Monthly Test",
    totalMarks: 800,
    obtainedMarks: 694,
    percentage: 86.75,
    gpa: 4.8,
    grade: "A",
    position: 3,
    attendance: 96,
    status: "Pass",
    subjects: [
      { subject: "English Language", marks: 88, fullMarks: 100, grade: "A" },
      { subject: "English Literature", marks: 84, fullMarks: 100, grade: "A" },
      { subject: "Mathematics", marks: 93, fullMarks: 100, grade: "A+" },
      { subject: "General Science", marks: 89, fullMarks: 100, grade: "A" },
      { subject: "Bangla", marks: 85, fullMarks: 100, grade: "A" },
      { subject: "Islamic Studies", marks: 90, fullMarks: 100, grade: "A+" },
      { subject: "ICT", marks: 87, fullMarks: 100, grade: "A" },
      {
        subject: "Arabic",
        marks: 78,
        fullMarks: 100,
        grade: "A-",
      },
    ],
  },

  {
    id: 8,
    studentId: "STD-2026-003",
    admissionNo: "ADM24003",
    roll: 3,
    name: "Zayan Chowdhury",
    class: "Grade 8",
    section: "A",
    academicYear: "2025-2026",
    examType: "Final Examination",
    totalMarks: 800,
    obtainedMarks: 733,
    percentage: 91.63,
    gpa: 5,
    grade: "A+",
    position: 2,
    attendance: 97,
    status: "Pass",
    subjects: [
      { subject: "English Language", marks: 92, fullMarks: 100, grade: "A+" },
      { subject: "English Literature", marks: 90, fullMarks: 100, grade: "A+" },
      { subject: "Mathematics", marks: 98, fullMarks: 100, grade: "A+" },
      { subject: "General Science", marks: 94, fullMarks: 100, grade: "A+" },
      { subject: "Bangla", marks: 89, fullMarks: 100, grade: "A" },
      { subject: "Islamic Studies", marks: 95, fullMarks: 100, grade: "A+" },
      { subject: "ICT", marks: 91, fullMarks: 100, grade: "A+" },
      {
        subject: "Arabic",
        marks: 84,
        fullMarks: 100,
        grade: "A",
      },
    ],
  },

  {
    id: 9,
    studentId: "STD-2026-004",
    admissionNo: "ADM24004",
    roll: 4,
    name: "Nafisa Islam",
    class: "Grade 8",
    section: "A",
    academicYear: "2025-2026",
    examType: "Final Examination",

    totalMarks: 800,
    obtainedMarks: 706,
    percentage: 88.25,
    gpa: 5,
    grade: "A",
    position: 4,
    attendance: 96,
    status: "Pass",

    subjects: [
      { subject: "English Language", marks: 89, fullMarks: 100, grade: "A" },
      { subject: "English Literature", marks: 86, fullMarks: 100, grade: "A" },
      { subject: "Mathematics", marks: 94, fullMarks: 100, grade: "A+" },
      { subject: "General Science", marks: 91, fullMarks: 100, grade: "A+" },
      { subject: "Bangla", marks: 84, fullMarks: 100, grade: "A" },
      { subject: "Islamic Studies", marks: 90, fullMarks: 100, grade: "A+" },
      { subject: "ICT", marks: 88, fullMarks: 100, grade: "A" },
      {
        subject: "Arabic",
        marks: 84,
        fullMarks: 100,
        grade: "A",
      },
    ],
  },
];
